### ISSUE TITLE
LifecycleExecutionException when there's no xprocspec tests

### ISSUE THREAD

**Issue by josteinaj** [daisy/xproc-maven-plugin#11]
When there's no xprocspec tests in `src/test/xprocspec`, I get this error:

```
➜ mvn clean test -X
(...)
-------------------------------------------------------
 X P R O C S P E C   T E S T S
-------------------------------------------------------
There are no tests to run.

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.292s
[INFO] Finished at: Fri Jun 27 11:31:17 CEST 2014
[INFO] Final Memory: 10M/301M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.daisy.maven:xproc-maven-plugin:1.0.0:xprocspec (default) on project hello-world: Execution default of goal org.daisy.maven:xproc-maven-plugin:1.0.0:xprocspec failed: String index out of range: -1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.daisy.maven:xproc-maven-plugin:1.0.0:xprocspec (default) on project hello-world: Execution default of goal org.daisy.maven:xproc-maven-plugin:1.0.0:xprocspec failed: String index out of range: -1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.daisy.maven:xproc-maven-plugin:1.0.0:xprocspec failed: String index out of range: -1
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:762)
	at java.lang.StringBuilder.deleteCharAt(StringBuilder.java:258)
	at org.daisy.maven.xproc.xprocspec.XProcSpecRunner.run(XProcSpecRunner.java:136)
	at org.daisy.maven.xproc.xprocspec.XProcSpecRunner.run(XProcSpecRunner.java:168)
	at org.daisy.maven.xproc.plugin.XProcSpecMojo.execute(XProcSpecMojo.java:122)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by bertfrees** [comment]
Should be fixed now
